/*
	Author: @ThanhHang
*/
-- ===================================================================================

 -- USE Mikrokosmos;

-- ===================================================================================

insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-01', 'Book-01', 1, 25);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-02', 'Book-02', 4, 24);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-03', 'Book-03', 2, 23);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-04', 'Book-04', 6, 22);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-05', 'Book-05', 3, 21);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-06', 'Book-06', 1, 20);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-07', 'Book-07', 9, 19);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-08', 'Book-08', 2, 18);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-09', 'Book-09', 5, 17);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-010', 'Book-010', 6, 16);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-011', 'Book-011', 2, 15);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-012', 'Book-012', 3, 14);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-013', 'Book-013', 7, 13);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-014', 'Book-014', 1, 14);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-015', 'Book-015', 3, 11);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-016', 'Book-016', 7, 10);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-017', 'Book-017', 8, 9);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-018', 'Book-018', 3, 8);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-019', 'Book-019', 5, 7);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-020', 'Book-020', 6, 20);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-021', 'Book-021', 7, 21);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-022', 'Book-022', 1, 4);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-023', 'Book-023', 5, 3);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-024', 'Book-024', 2, 24);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-025', 'Book-025', 8, 1);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-026', 'Book-026', 3, 26);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-027', 'Book-027', 8, 27);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-028', 'Book-028', 2, 28);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-029', 'Book-029', 7, 29);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-030', 'Book-030', 3, 15);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-031', 'Book-031', 6, 12);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-032', 'Book-032', 3, 15);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-033', 'Book-033', 8, 20);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-034', 'Book-034', 3, 13);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-035', 'Book-035', 7, 7);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-036', 'Book-036', 2, 9);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-037', 'Book-037', 7, 5);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-038', 'Book-038', 1, 4);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-039', 'Book-039', 8, 9);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-040', 'Book-040', 9, 10);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-041', 'Book-041', 2, 3);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-042', 'Book-042', 6, 12);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-043', 'Book-043', 3, 13);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-044', 'Book-044', 5, 24);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-045', 'Book-045', 4, 15);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-046', 'Book-046', 6, 6);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-047', 'Book-047', 8, 27);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-048', 'Book-048', 2, 28);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-049', 'Book-049', 2, 20);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-050', 'Book-050', 1, 26);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-051', 'Book-051', 6, 1);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-052', 'Book-052', 1, 22);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-053', 'Book-053', 3, 12);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-054', 'Book-054', 6, 25);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-055', 'Book-055', 1, 5);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-056', 'Book-056', 3, 5);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-057', 'Book-057', 8, 7);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-058', 'Book-058', 2, 20);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-059', 'Book-059', 9, 9);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-060', 'Book-060', 7, 12);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-061', 'Book-061', 6, 11);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-062', 'Book-062', 9, 19);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-063', 'Book-063', 2, 10);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-064', 'Book-064', 5, 14);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-065', 'Book-065', 2, 16);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-066', 'Book-066', 6, 16);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-067', 'Book-067', 3, 6);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-068', 'Book-068', 6, 18);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-069', 'Book-069', 6, 20);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-070', 'Book-070', 3, 20);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-071', 'Book-071', 6, 21);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-072', 'Book-072', 10, 29);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-073', 'Book-073', 3, 23);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-074', 'Book-074', 6, 25);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-043', 'Book-075', 2, 25);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-023', 'Book-076', 3, 10);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-054', 'Book-077', 4, 0);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-012', 'Book-078', 6, 0);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-065', 'Book-079', 8, 1);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-019', 'Book-080', 9, 10);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-029', 'Book-081', 2, 0);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-050', 'Book-082', 3, 12);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-057', 'Book-083', 4, 17);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-071', 'Book-084', 6, 17);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-045', 'Book-085', 2, 0);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-039', 'Book-01', 3, 30);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-020', 'Book-03', 7, 17);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-050', 'Book-05', 2, 13);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-040', 'Book-06', 8, 10);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-060', 'Book-08', 3, 11);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-010', 'Book-10', 7, 10);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-030', 'Book-013', 4, 9);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-061', 'Book-015', 6, 18);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-072', 'Book-026', 7, 20);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-01', 'Book-019', 2, 0);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-09', 'Book-021', 3, 5);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-021', 'Book-023', 1, 14);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-059', 'Book-027', 6, 23);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-04', 'Book-028', 7, 0);
insert into InvoiceDetails(InvoiceID, BookID, Quantity, Discount) value('Invoice-021', 'Book-033', 1, 0);

select * from invoicedetails;
