/*
	Author: @ThanhHang
*/
-- ===================================================================================

  -- USE Mikrokosmos;

-- ===================================================================================
-- Author-0
-- Category-0

Call sp_Books_insert('Là Người Phụ Nữ Như Tôi Mong Muốn', 'bk001.jpg', 'Câu chuyện cuộc đời của nữ cường nhân đình đám trong làng thời trang thế giới', 'Categorie-07', 'Author-050', 'abc');
Call sp_Books_insert('Rock Hà Nội, Bolero Sài Gòn - Câu Chuyện Tân Nhạc Việt Nam', 'bk002.jpg', 'Câu chuyện tân nhạc Việt Nam hé mở những hiện tượng và cột mốc của âm nhạc dưới góc nhìn độc đáo, tỉ mỉ và mê say của một nhà nghiên cứu độc lập người Mỹ.', 'Categorie-07', 'Author-049', 'abc');
Call sp_Books_insert('Thực Hành Giáo Dục Nhân Cách', 'bk003.jpg','THỰC HÀNH GIÁO DỤC NHÂN CÁCH là một cuốn cẩm nang đơn giản nhưng hữu ích, dành cho các bậc phụ huynh, giáo viên mầm non', 'Categorie-05', 'Author-048', 'abc');
Call sp_Books_insert('Phát triển khả năng sáng tạo', 'bk004.jpg', 'Bộ sách Phát Triển Trí Tuệ Của Trẻ Qua Trò Chơi Dán Hình (4-6 tuổi) giúp trẻ phát triển khả năng Sáng tạo, Toán học, Ngôn Ngữ, Tư duy', 'Categorie-05', 'Author-047', 'abc');
Call sp_Books_insert('Phát Triển Khả Năng Toán Học', 'bk005.jpg', 'Bộ sách Phát Triển Trí Tuệ Của Trẻ Qua Trò Chơi Dán Hình (4-6 tuổi) giúp trẻ phát triển khả năng Sáng tạo, Toán học, Ngôn Ngữ, Tư duy', 'Categorie-05', 'Author-047', 'abc');
Call sp_Books_insert('Bé Ngoan Rèn Thói Quen Tốt: Học Cách Tập Trung - Grace Said Focus', 'bk006.jpg', 'How can we stay focused on everything?', 'Categorie-07', 'Author-046', 'abc');
Call sp_Books_insert('Bé Ngoan Rèn Thói Quen Tốt: Học Cách Kiên Trì - Grace Said Persistence', 'bk007.jpg', 'Dont give up until reaching your goal!', 'Categorie-07', 'Author-046', 'abc');
Call sp_Books_insert('Bản Thiết Kế Vĩ Đại', 'bk008.jpg', 'Nội dung cuốn sách, như tác giả nói ngay từ dòng đầu tiên của chương một, là chuyện “Bí ẩn của kiếp nhân sinh”', 'Categorie-08', 'Author-045', 'abc');
Call sp_Books_insert('Vũ Trụ Trong Vỏ Hạt Dẻ', 'bk009.jpg', 'Trong quyển “Vũ trụ trong vỏ hạt dẻ”, Stephen Hawking đưa chúng ta đến khía cạnh nổi trội của vật lý lý thuyết, ở đó sự thất thường còn lạ lùng hơn hư cấu, để giảng giải - bằng ngôn ngữ bình thường', 'Categorie-08', 'Author-045', 'abc');
Call sp_Books_insert('Stephen Hawking - Một Trí Tuệ Không Giới Hạn', 'bk010.jpg', 'Một quyển sách phù hợp cho những độc giả yêu thích bộ môn khoa học vũ trụ, hay vẫn luôn dõi theo những tấm gương vượt khó.', 'Categorie-08', 'Author-045', 'abc');
Call sp_Books_insert('Ung Thư - Tin Đồn & Sự Thật', 'bk011.jpg', 'qua cuốn sách Ung thư: Tin đồn và Sự thật, đội ngũ các bác sĩ, nhà khoa học trong nhóm Ruy Băng Tím sẽ lý giải cho những tin đồn đang lan truyền hiện nay', 'Categorie-07', 'Author-044', 'abc');
Call sp_Books_insert('Robot-Proof: Higher Education in the Age of Artificial Intelligence', 'bk012.jpg', 'How to educate the next generation of college students to invent, to create, and to discover—filling needs that even the most sophisticated robot cannot.', 'Categorie-08', 'Author-043', 'abc');
Call sp_Books_insert('The Order of Time', 'bk013.jpg', 'From the bestselling author of Seven Brief Lessons on Physics, comes a concise, elegant exploration of time.	', 'Categorie-07', 'Author-042', 'abc');
Call sp_Books_insert('Reality Is Not What It Seems: The Journey to Quantum Gravity', 'bk014.jpg', 'From the New York Times–bestselling author of Seven Brief Lessons on Physics and The Order of Time, a closer look at the mind-bending nature of the universe.', 'Categorie-01', 'Author-042', 'abc');
Call sp_Books_insert('Amazing Truths: How Science and the Bible Agree', 'bk015.jpg', 'Dr. Michael Guillen, former ABC News Science Editor and Harvard physics instructor, is host of the History Channels Where Did It Come From?', 'Categorie-08', 'Author-041', 'abc');
Call sp_Books_insert('Khoa Học Khám Phá - 5 Phương Trình Làm Thay Đổi Thế Giới', 'bk016.jpg', 'Cuốn sách mô tả về năm phương trình nổi tiếng có sức chuyển động thế giới', 'Categorie-08', 'Author-041', 'abc');
Call sp_Books_insert('Chiến Tranh Tiền Tệ - Ai Thực Sự Là Người Giàu Nhất Thế Giới?', 'bk017.jpg', 'Một cuốn sách bổ ích cho các chuyên gia quản lý tài chính, các nhà quản trị doanh nghiệp, các nhà đầu tư nhỏ, các giáo viên giảng dạy về tài chính – ngân hàng cũng như sinh viên các trường kinh tế', 'Categorie-04', 'Author-040', 'abc');
Call sp_Books_insert('Dám Bị Ghét', 'bk018.jpg', 'TẠI SAO BẠN CỨ PHẢI SỐNG THEO KHUÔN MẪU NGƯỜI KHÁC ĐẶT RA?', 'Categorie-02', 'Author-039', 'abc');
Call sp_Books_insert('Dám Hạnh Phúc', 'bk019.jpg', 'Chỉ có điều, chúng ta không thể hưởng thụ hạnh phúc nếu chỉ đứng yên tại chỗ. Cần phải tiếp tục tiến bước trên con đường mình đã đặt chân lên', 'Categorie-02', 'Author-039', 'abc');
Call sp_Books_insert('Đọc Vị Bất Kỳ Ai', 'bk020.jpg', 'ĐỌC người khác là một trong những công cụ quan trọng, có giá trị nhất, giúp ích cho bạn trong mọi khía cạnh của cuộc sống', 'Categorie-02', 'Author-038', 'abc');
Call sp_Books_insert('Sang Chấn Tâm Lý - Hiểu Để Chữa Lành', 'bk021.jpg', 'Một tác phẩm kinh điển của tâm thần học hiện đại, là một công trình khoa học công phu và nghiêm túc, trải rộng trên nhiều lĩnh vực - tâm lý học thần kinh, tâm lý học phát triển, tâm bệnh học, tâm lý trị liệu', 'Categorie-01', 'Author-037', 'abc');
Call sp_Books_insert('Từ Tốt Đến Vĩ Đại - Jim Collins', 'bk022.jpg', 'Mỗi kết luận của nhóm nghiên cứu đều hữu ích, vượt thời gian, ý nghĩa vô cùng to lớn đối với mọi lãnh đạo và quản lý ở mọi loại hình công ty', 'Categorie-07', 'Author-036', 'abc');
Call sp_Books_insert('How The Mighty Fall: And Why Some Companies Never Give In', 'bk023.jpg', 'Decline can be avoided. Decline can be detected. Decline can be reversed.', 'Categorie-04', 'Author-036', 'abc');
Call sp_Books_insert('Vĩ Đại Do Lựa Chọn', 'bk024.jpg', 'Họ sống và làm việc theo ba yếu tố cân bằng nhau: kiên định với nguyên tắc, sáng tạo theo kinh nghiệm và biết sợ hãi một cách hữu ích.', 'Categorie-02', 'Author-036', 'abc');
Call sp_Books_insert('Giáo Trình Kỹ Thuật Chuyển Mạch Số', 'bk025.jpg', 'Kỹ thuật viễn thông là một ngành đã phát triển rất mạnh mẽ trong những năm gần đây...', 'Categorie-06', 'Author-035', 'abc');
Call sp_Books_insert('Giáo Trình Mạch Điện Tử Cơ Bản', 'bk026.jpg', 'Mạch điện tử cơbản là giáo trình được biên soạn theo đề cương do Sở Giáo dục và Đào tạo thành phố xây dựng và thông qua...', 'Categorie-06', 'Author-035', 'abc');
Call sp_Books_insert('Thơ Hồ Thế Hà & Giấc Mơ Cỏ Hát - Chuyên Luận', 'bk027.jpg', 'Nhà thơ Hồ Thế Hà sinh ngày 10-6-1955 tại Tỉnh Bình Định, nước Việt Nam...', 'Categorie-03', 'Author-034', 'abc');
Call sp_Books_insert('Ông Già Và Biển Cả ', 'bk028.jpg', 'Tác phẩm ca ngợi niềm tin, sức lao động và khát vọng của con người...', 'Categorie-03', 'Author-033', 'abc');
Call sp_Books_insert('Giã Từ Vũ Khí', 'bk029.jpg', 'Một cuốn tiểu thuyết bán tự truyện của nhà văn Ernest Hemingway viết năm 1929', 'Categorie-03', 'Author-033', 'abc');
Call sp_Books_insert('Atlat Địa Lí Việt Nam', 'bk030.jpg', 'Bản đồ Việt Nam', 'Categorie-06', 'Author-032', 'abc');
Call sp_Books_insert('Trước Vòng Chung Kết', 'bk031.jpg', 'Tràn ngập không khí bóng đá, không khí vỉa hè… đậm mùi hào hiệp, thượng võ....', 'Categorie-03', 'Author-031', 'abc');
Call sp_Books_insert('Thiên Thần Nhỏ Của Tôi ', 'bk032.jpg', 'Khi dọn về ngôi nhà mới, Kha có một cô bạn nghèo sống trong ngõ hẻm gần đó....', 'Categorie-03', 'Author-031', 'abc');
Call sp_Books_insert('Ticket To Childhood', 'bk033.jpg', 'The story of a man looking back on his life, Ticket to Childhood captures the texture of childhood in all of its richness...', 'Categorie-03', 'Author-031', 'abc');
Call sp_Books_insert('Vụ Án Lerouge', 'bk034.jpg', 'Một câu đố được bọc bên trong một bí ẩn. Một bí ẩn được bọc bên trong một bí ẩn khác. Hai người mẹ, hai đứa con trai, một người cha, một kẻ giết người...', 'Categorie-03', 'Author-030', 'abc');
Call sp_Books_insert('Tội Ác Ở Orcival', 'bk035.jpg', 'Một buổi sáng mùa hè ở Orcival, người ta phát hiện thi thể biến dạng của nữ bá tước Trémorel bên bờ sông Sein. Cách đó không xa lâu đài của nạn nhân bị xới tung, còn ngài bá tước thì biệt vô âm tín.', 'Categorie-03', 'Author-030', 'abc');
Call sp_Books_insert('Bước Đường Của Cải Lương', 'bk036.jpg', '“Tuy mới hình thành được gần 100 năm nhưng cải lương đã có một chỗ đứng trong lãnh vực âm nhạc cổ truyền Việt Nam”.', 'Categorie-07', 'Author-029', 'abc');
Call sp_Books_insert('Đường Tự Do Tài Chính', 'bk037.jpg', 'Bodo Schäfer đã viết trong cuốn sách này rằng: “GIÀU CÓ LÀ QUYỀN CỦA BẠN NGAY TỪ KHI CHÀO ĐỜI! ', 'Categorie-04', 'Author-028', 'abc');
Call sp_Books_insert('Bí quyết để thành đạt', 'bk038.jpg', 'Với những lời khuyên chân tình, bổ ích trong cuốn sách Bí quyết để thành đạt của Bodo Schaefer đồng thời cũng là tác giả của cuốn sách Cách làm giàu nổi tiếng bán chạy nhất ở châu Âu:', 'Categorie-04', 'Author-028', 'abc');
Call sp_Books_insert('Những Linh Hồn Chết', 'bk039.jpg', 'Những linh hồn chết là câu hỏi lớn mà Nikolai Gogol đặt ra không chỉ cho người Nga cùng thời với ông mà cho con người ở mọi nước, mọi thời:', 'Categorie-03', 'Author-027', 'abc');
Call sp_Books_insert('Le Nez/Le Manteau', 'bk040.jpg', '...', 'Categorie-03', 'Author-027', 'abc');
Call sp_Books_insert('Cuộc Trốn Chạy Của Josef Mengele', 'bk041.jpg', 'Những thứ còn tệ hơn cả cái chết...', 'Categorie-03', 'Author-026', 'abc');
Call sp_Books_insert('Chân Đi Không Mỏi', 'bk042.jpg', 'Campuchia trong tôi cứ như một cuốn sách mà không bao giờ tôi đọc hết, cũng chẳng bao giờ muốn đọc hết...', 'Categorie-03', 'Author-025', 'abc');
Call sp_Books_insert('Đếm Sao', 'bk043.jpg', 'Bạn có một cô bạn tuy chân ngắn nhưng vẫn cố gắng chạy cùng mình đến tận cuối phố không nào?', 'Categorie-05', 'Author-024', 'abc');
Call sp_Books_insert('Người Truyền Ký Ức ', 'bk044.jpg', 'Cho dù một ai đã từng đọc những lời giới thiệu ngắn gọn xung quanh cuốn sách, không đọc cũng không thể nào cảm nhận hết sự kỳ lạ của nó. Người truyền ký ức tuyệt vời ở trí tưởng tưởng và những thông điệp mang theo', 'Categorie-05', 'Author-024', 'abc');
Call sp_Books_insert('The Giver (Essential Modern Classics)', 'bk045.jpg', 'THE GIVER is the classic award-winning novel that inspired the dystopian genre and a major motion picture adaptation for 2014 starring Jeff Bridges, Meryl Streep, Katie Holmes and Taylor Swift.', 'Categorie-05', 'Author-024', 'abc');
Call sp_Books_insert('Sức Mạnh Của Ngôn Từ ', 'bk046.jpg', 'Để đạt được những điều bạn mong muốn, giao tiếp chính là chiếc chìa khóa đầu tiên', 'Categorie-02', 'Author-023', 'abc');
Call sp_Books_insert('Bác Hồ Với Công Việc Văn Phòng', 'bk047.jpg', 'Chủ tịch Hồ Chí Minh – Bác Hồ kính yêu của chúng ta là anh hùng dân tộc vĩ đại, nhà tư tưởng lỗi lạc, nhà văn hóa kiệt xuất và là tấm gương đạo đức ngời sáng.', 'Categorie-07', 'Author-022', 'abc');
Call sp_Books_insert('Trẻ Em Như Ngọc Như Gương - Cách Giáo Dục Dạy Trẻ Em Hiệu Quả Nhất', 'bk048.jpg', 'Các bậc cha mẹ nên thay đổi như thế nào để phù hợp với sự ra đời và lớn lên của đứa trẻ.', 'Categorie-05', 'Author-021', 'abc');
Call sp_Books_insert('Hai Vạn Dặm Dưới Biển', 'bk049.jpg', 'Hai Vạn Dặm Dưới Biển kể về câu chuyện thám hiểm đại dương của nhà bảo tàng học người Pháp, giáo sư PierreAronnax.', 'Categorie-03', 'Author-020', 'abc');
Call sp_Books_insert('80 Ngày Vòng Quanh Thế Giới ', 'bk050.jpg', 'Câu chuyện khoa học viễn tưởng dự đoán trước được tương lai.', 'Categorie-03', 'Author-020', 'abc');
Call sp_Books_insert('Ngọc Phương Nam', 'bk051.jpg', 'Ngọc Phương Nam lại chứa đựng một số phương diện hiếm thấy ở ngòi bút nhà văn vĩ đại của dòng văn chương khoa học viễn tưởng.', 'Categorie-03', 'Author-020', 'abc');
Call sp_Books_insert('Câu Chuyện Khoa Học: Chim Xây Tổ', 'bk052.jpg', 'Cuốn sách không chỉ giới thiệu cho trẻ biết về cuộc sống của loài chim mà còn giúp bé hiểu các khái niệm khoa học về lực kéo, lực đẩy…', 'Categorie-05', 'Author-019', 'abc');
Call sp_Books_insert('Câu Chuyện Khoa Học: Sâu Bướm Và Hạt Đậu', 'bk053.jpg', 'SÂU BƯỚM VÀ HẠT ĐẬU là cuốn sách giới thiệu đến độc giả nhỏ tuổi về sự phát triển và vòng đời của một con sâu bướm và một hạt đậu.', 'Categorie-05', 'Author-019', 'abc');
Call sp_Books_insert('Câu Chuyện Khoa Học: Bạn Cáo Trong Đêm', 'bk054.jpg', 'BẠN CÁO TRONG ĐÊM lại là một câu chuyện khoa học thú vị khác, các kiến thức khoa học được đề cập trong câu chuyện như sự thay đổi của bầu trời cũng như các hoạt động của con người, cây cối, con vật vào ban ngày và đêm.', 'Categorie-05', 'Author-019', 'abc');
Call sp_Books_insert('Bé Khám Phá Khoa Học Qua Truyện Đồng Thoại, Bốn Mùa Rực Rỡ - Mùa Thu, Mùa Thu Hoạch', 'bk055.jpg', 'Bộ “Bốn mùa rực rỡ” gồm 04 cuốn giúp trẻ nhận thức và cảm nhận được vẻ đẹp của từng mùa trong năm', 'Categorie-05', 'Author-018', 'abc');
Call sp_Books_insert('Bé Khám Phá Khoa Học Qua Truyện Đồng Thoại, Bốn Mùa Rực Rỡ - Mùa Đông Giá Lạnh', 'bk056.jpg', 'Bộ “Bốn mùa rực rỡ” gồm 04 cuốn giúp trẻ nhận thức và cảm nhận được vẻ đẹp của từng mùa trong năm', 'Categorie-05', 'Author-018', 'abc');
Call sp_Books_insert('Bé Khám Phá Khoa Học Qua Truyện Đồng Thoại, Bốn Mùa Rực Rỡ - Mùa Xuân Rộn Rã', 'bk057.jpg', 'Bộ “Bốn mùa rực rỡ” gồm 04 cuốn giúp trẻ nhận thức và cảm nhận được vẻ đẹp của từng mùa trong năm', 'Categorie-05', 'Author-018', 'abc');
Call sp_Books_insert('Brant Pinvidic', 'bk058.jpg', 'Vậy làm thế nào để thu hút và duy trì được sự chú ý của người nghe?', 'Categorie-01', 'Author-017', 'abc');
Call sp_Books_insert('Khéo Ăn Khéo Nói Sẽ Có Được Thiên Hạ', 'bk059.jpg', 'Khéo ăn nói giống như sở hữu loại “dầu bôi trơn” đảm bảo các mối quan hệ của bạn “vận hành” trơn tru. Không khéo ăn nói, gặp chuyện nhỏ mắc trở ngại, gặp chuyện lớn vấp thất bại.', 'Categorie-02', 'Author-016', 'abc');
Call sp_Books_insert('9 Nguyên Tắc Làm Một Người Chồng Tốt', 'bk060.jpg', '"Hôn nhân là nấm mồ của tình yêu”', 'Categorie-02', 'Author-016', 'abc');
Call sp_Books_insert('Nick Vujicic - Cuộc Sống Không Giới Hạn', 'bk061.jpg', 'Vốn dĩ cuộc sống thực sự không có giới hạn nào cả, chỉ cần bạn có đủ sức mạnh, ý chí và khả năng để chinh phục thì giới hạn cuộc sống vĩnh viễn nằm ở điểm vô cực.', 'Categorie-03', 'Author-015', 'abc');
Call sp_Books_insert('Love Without Limits: A Remarkable Story of True Love Conquering All', 'bk062.jpg', 'It Doesnt Take a Perfect Person to Find a Perfect Love Even though he was born without arms or legs, Nick Vujicic created a "ridiculously good life."', 'Categorie-03', 'Author-015', 'abc');
Call sp_Books_insert('Be The Hands And Feet', 'bk063.jpg', 'Nothing in life is as exciting and satisfying as introducing Jesus to people who have never met him.', 'Categorie-03', 'Author-015', 'abc');
Call sp_Books_insert('Hành Trình Đến Vô Cực - Cuộc Sống Của Tôi Với Stephen Hawking. Câu Chuyện Thực Sự Đằng Sau “Thuyết Vạn Vật”', 'bk064.jpg', 'Với một thiên tài khoa học như vậy lại trong một cơ thể không “bình thường” của ông thì cuộc sống ngoài khoa học của ông sẽ như thế nào? ', 'Categorie-03', 'Author-014', 'abc');
Call sp_Books_insert('Để Khát Vọng Dẫn Lối - Hành Trình Cậu Bé Bán Báo Trở Thành Lãnh Đạo Tập Đoàn Tỷ Đô', 'bk065.jpg', 'Một cuốn sách đáng đọc cho những người trân trọng nỗ lực tự thân', 'Categorie-04', 'Author-013', 'abc');
Call sp_Books_insert('Chuyện Tôi - Hồi Ức Của Con Trai Nhà Văn Nguyễn Huy Tưởng', 'bk066.jpg', 'Quyển sách là hồi ức của tác giả Nguyễn Huy Thắng, con trai nhà văn Nguyễn Huy Tưởng..', 'Categorie-0', 'Author-012', 'abc');
Call sp_Books_insert('Thời Khắc Tươi Đẹp', 'bk067.jpg', 'Một cuốn hồi ký tuyệt vời về sự sống và cái chết, từ nhà thơ Nina Riggs, mẹ của hai đứa con trai và hậu duệ trực hệ của tác gia Ralph Waldo Emerson.', 'Categorie-03', 'Author-011', 'abc');
Call sp_Books_insert('25 Mô Hình MBA Căn Bản', 'bk068.jpg', 'Chương trình Thạc sĩ Quản trị Kinh doanh (MBA) là một trong những chương trình cao học được tìm kiếm nhiều nhất tại Việt Nam cũng như trên thế giới.', 'Categorie-04', 'Author-010', 'abc');
Call sp_Books_insert('MBA Trong Quản Lý Kinh Doanh', 'bk069.jpg', 'à một người nuôi dưỡng khát khao khởi nghiệp, hoặc muốn đưa doanh nghiệp của mình tiến lên tầm cao mới, bạn không thể không trang bị những kiến thức mang tính nền tảng cho kinh doanh này.', 'Categorie-04', 'Author-010', 'abc');
Call sp_Books_insert('Combo Thiết Lập Internet Vạn Vật Trong Doanh Nghiệp + Khi Bạn Là CEO – 100 Câu Hỏi Tiêu Biểu', 'bk070.jpg', '.....', 'Categorie-04', 'Author-09', 'abc');
Call sp_Books_insert('Stephen Hawking: Một Trí Tuệ Không Giới Hạn', 'bk071.jpg', 'Một quyển sách phù hợp cho những độc giả yêu thích bộ môn khoa học vũ trụ, hay vẫn luôn dõi theo những tấm gương vượt khó. ', 'Categorie-01', 'Author-08', 'abc');
Call sp_Books_insert('Thói Quen Thứ 8 - Từ Hiệu Quả Đến Vĩ Đại ', 'bk072.jpg', 'Kỷ Nguyên Lao động Tri thức, đòi hỏi chúng ta phải vượt qua sự Hiệu quả để vươn đến sự Vĩ đại', 'Categorie-01', 'Author-08', 'abc');
Call sp_Books_insert('Lỗ Đen: Các Bài Tuyết Giảng Trên Đài', 'bk073.jpg', 'Sách tập hợp hai bài nói chuyện của nhà vật lý vĩ đại Stephen Hawking trên BBC vào đầu năm 2016.', 'Categorie-01', 'Author-08', 'abc');
Call sp_Books_insert('Thế Hệ Y Lên Ngôi', 'bk074.jpg', 'Tổ chức của bạn đã sẵn sàng cho những điều sắp tới chưa?', 'Categorie-01', 'Author-07', 'abc');
Call sp_Books_insert('Lập Kế Hoạch Tổ Chức Công Việc Hiệu Quả', 'bk075.jpg', 'Lập kế hoạch tổ chức công việc hiệu quả” sẽ giúp bạn học hỏi tất cả những bí quyết để gắn kết các nhân viên giỏi và truyền cho họ cảm hứng làm việc tốt nhất', 'Categorie-01', 'Author-07', 'abc');
Call sp_Books_insert('Mưu Sự Tại Nhân', 'bk076.jpg', 'Mưu sự tại nhân, hành sự tại thiên', 'Categorie-02', 'Author-06', 'abc');
Call sp_Books_insert('Bí Quyết Dùng Người - Chiêu Dụng "Hiền Tài" - Tổ Chức Nhân Lực', 'bk077.jpg', 'Con người là tài nguyên quý giá nhất', 'Categorie-02', 'Author-06', 'abc');
Call sp_Books_insert('Trí Tuệ Khổng Tử', 'bk078.jpg', 'Những bài học quý báu được đúc rút từ kinh nghiệm sống, sự trải nghiệm của một tâm hồn mẫn tiệp của Khổng Tử được tập hợp trong cuốn sách  "Trí tuệ Khổng Tử".', 'Categorie-02', 'Author-06', 'abc');
Call sp_Books_insert('Đàm Phán Bậc Thầy Cả Hai Cùng Thắng - Tái Bản 2019', 'bk079.jpg', 'Đàm phán kỳ thực là một trò chơi với đầy đủ các luật lệ - một trò chơi xoay quanh các kỹ năng, cơ hội và rủi ro', 'Categorie-02', 'Author-05', 'abc');
Call sp_Books_insert('Hỏi Đáp Cùng Em- Vạn Vật Hoạt Động Thế Nào?', 'bk080.jpg', 'Bộ sách được đóng góp bởi các chuyên gia hàng đầu trong các lĩnh vực của nước Pháp', 'Categorie-04', 'Author-04', 'abc');
Call sp_Books_insert('Sang Chấn Tâm Lý - Hiểu Để Chữa Lành', 'bk081.jpg', 'Một tác phẩm kinh điển của tâm thần học hiện đại, là một công trình khoa học công phu và nghiêm túc, trải rộng trên nhiều lĩnh vực - tâm lý học thần kinh, tâm lý học phát triển, tâm bệnh học, tâm lý trị liệ', 'Categorie-01', 'Author-03', 'abc');
Call sp_Books_insert('Tâm Lý Học', 'bk082.jpg', 'Tâm lý học là ngành khoa học nghiên cứu hoạt động, tinh thần và tư tưởng của con người ...', 'Categorie-01', 'Author-02', 'abc');
Call sp_Books_insert('Osho - Lòng Trắc Ẩn', 'bk083.jpg', 'Trong tập sách thứ mươi trong bộ sách nổi tiếng "Lối sông mới" của OSHO, ông đã đưa ra một cái nhin sâu sắc và kahsc biệt về bản chất của lòng trắc ẩn.', 'Categorie-07', 'Author-01', 'abc');
Call sp_Books_insert('Osho - Sự Hiểu Biết', 'bk084.jpg', 'Trước tiên, cần phải hiểu rằng tri thức không phải là sự hiểu biết. Tri thức là biểu hiện của sự hiểu biết.', 'Categorie-07', 'Author-01', 'abc');
Call sp_Books_insert('Osho - Niềm Vui Sướng', 'bk085.jpg', '....', 'Categorie-07', 'Author-01', 'abc');


select * from books;